// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace MeuPedido.iOS
{
    public partial class CatalogoTableViewController : UITableViewController
	{
		public CatalogoTableViewController (IntPtr handle) : base (handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            catalogoListTableView.DataSource = this;
            //this.TableView.DataSource = this;
        }
        public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
        {
            UITableViewCell cell = tableView.DequeueReusableCell("catalogoTableViewCell") as CatalogoTableViewCell;

            return cell;
        }

        public override nint RowsInSection(UITableView tableview, nint section)
        {
            return 32;
        }

        public override nfloat GetHeightForRow(UITableView tableView, NSIndexPath indexPath)
        {
            return 120;
        }
    }
}
